[package]
name = "libmusic"
version = "1.0.0"
edition = "2021"

[lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
unused = "warn"

[lints.clippy]
unusual_byte_groupings = "allow"
all = "warn"

[[bin]]
name = "music"
path = "main.rs"
